/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function callMe(): void
export declare function fibonacci(n: number): number
export declare function readFile(path: string): string
